# Generated by Django 5.0.6 on 2024-06-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
